In [1]:
import sys
sys.path.append("../model")
from dual_attention import PositionalEncoding


In [2]:
pos_enc = PositionalEncoding(emb_size=128, dropout=0.1, maxlen=144)

In [6]:
import torch
token_embedding = torch.randn(4,256,128)

In [7]:
token_embedding.shape

torch.Size([4, 256, 128])

In [8]:
pos_enc(token_embedding).shape

torch.Size([4, 256, 128])

In [10]:
pos_enc.pos_embedding.shape

torch.Size([144, 1, 128])

In [18]:
new_emb = pos_enc.pos_embedding.squeeze(1)
new_emb.shape

torch.Size([144, 128])

tensor([[ 0,  1,  2,  6, -1],
        [ 0,  1,  2,  3,  5]])

In [34]:
new_emb[torch.LongTensor([[0,1,2,6,-1], [0,1,2,3,5]])].shape

torch.Size([2, 5, 128])

In [23]:
idx = torch.randint(0, 144, (2, 5))  # (batch_size, x)
idx = idx.t()
idx.shape

torch.Size([5, 2])

In [24]:
idx

tensor([[ 84,  27],
        [ 91, 133],
        [ 71,  87],
        [131, 133],
        [ 57,  32]])

In [25]:
new_emb[idx].shape

torch.Size([5, 2, 128])

In [14]:
pos_enc.pos_embedding

tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
           0.0000e+00,  1.0000e+00]],

        [[ 8.4147e-01,  5.4030e-01,  7.6172e-01,  ...,  1.0000e+00,
           1.1548e-04,  1.0000e+00]],

        [[ 9.0930e-01, -4.1615e-01,  9.8705e-01,  ...,  1.0000e+00,
           2.3096e-04,  1.0000e+00]],

        ...,

        [[ 3.6317e-01, -9.3172e-01,  4.0881e-01,  ...,  9.9982e-01,
           1.6282e-02,  9.9987e-01]],

        [[-5.8780e-01, -8.0901e-01, -4.3029e-01,  ...,  9.9982e-01,
           1.6397e-02,  9.9987e-01]],

        [[-9.9835e-01,  5.7503e-02, -9.6639e-01,  ...,  9.9982e-01,
           1.6513e-02,  9.9986e-01]]])

In [17]:
pos_enc.pos_embedding[[[0,1,2,6,-1], [0,1,2,3,5]]].shape

IndexError: index 1 is out of bounds for dimension 1 with size 1

In [9]:
pos_enc.pos_embedding[:token_embedding.size(0)].shape

torch.Size([4, 1, 128])