In [ ]:
import pandas as pd
file_path = "/home/sagemaker-user/TrajCL/data/porto_20200"
trajs = pd.read_pickle(file_path)

In [ ]:
trajs.head()

In [ ]:
# from torch.utils.data import Dataset
# class TrajDataset(Dataset):
#     def __init__(self, data):
#         # data: DataFrame
#         self.data = data

#     def __getitem__(self, index):
#         return self.data.loc[index].merc_seq

#     def __len__(self):
#         return self.data.shape[0]

In [ ]:
# l = trajs.shape[0]
# train_idx = (int(l*0), 200000)
# eval_idx = (int(l*0.7), int(l*0.8))
# test_idx = (int(l*0.8), int(l*1.0))

# train = TrajDataset(trajs[train_idx[0]: train_idx[1]])
# eval = TrajDataset(trajs[eval_idx[0]: eval_idx[1]])
# test = TrajDataset(trajs[test_idx[0]: test_idx[1]])

In [ ]:
idx = 15
lon_lat_list = trajs['wgs_seq'][idx]

In [ ]:
lon_lat_list

In [ ]:
# !pip install folium
import folium

from folium import plugins
coordinates = [[x[0],x[1]] for x in lon_lat_list]
# Initialize map
m = folium.Map(location=coordinates[0], zoom_start=30)

folium.Marker(
    location=coordinates[0],
    popup="Start Location",
    icon=folium.Icon(color='green')  # Color can be 'red', 'blue', 'green', 'purple', etc.
).add_to(m)
# Add markers
for lat, lon in coordinates[1:]:
    folium.Marker([lat, lon]).add_to(m)

# Draw arrows between points
for i in range(len(coordinates) - 1):
    start = coordinates[i]
    end = coordinates[i + 1]

    # Draw the line
    line = folium.PolyLine([start, end], color="blue", weight=3, opacity=0.7).add_to(m)

    # Add directional arrow
    plugins.PolyLineTextPath(
        line,
        '➤',  # arrow symbol
        repeat=True,
        offset=7,
        attributes={'fill': 'blue', 'font-weight': 'bold', 'font-size': '16'}
    ).add_to(m)

# Save and show the map
m.save("map_with_arrows.html")
m


In [ ]:
import sys
sys.path.append("..")
from utils.cellspace import CellSpace

In [ ]:
import pickle

porto_cs = pickle.load(open("/home/sagemaker-user/TrajCL/data/porto_20200_cell100_cellspace.pkl","rb"))


In [ ]:
porto_cs

In [ ]:
porto_cs.size()

In [ ]:
lon_lat_list = [[-8.660646, 41.168574],
 [-8.661087, 41.167926],
 [-8.661231, 41.166576],
 [-8.660637, 41.166396],
 [-8.660295, 41.166819],
 [-8.658954, 41.168394],
 [-8.657649, 41.169906],
 [-8.656371, 41.171454],
 [-8.654706, 41.173479],
 [-8.653014, 41.17527],
 [-8.651349, 41.17644],
 [-8.652213, 41.177241],
 [-8.651358, 41.178069],
 [-8.65071, 41.178924],
 [-8.65125, 41.17968],
 [-8.649648, 41.180643],
 [-8.647515, 41.18193],
 [-8.644491, 41.183541],
 [-8.641701, 41.184108],
 [-8.638677, 41.182452],
 [-8.635284, 41.180589],
 [-8.632476, 41.179104],
 [-8.629983, 41.179365],
 [-8.629857, 41.179374],
 [-8.629857, 41.179374],
 [-8.629263, 41.179437],
 [-8.625996, 41.179779],
 [-8.622018, 41.180463],
 [-8.61885, 41.181912],
 [-8.617077, 41.182821],
 [-8.614215, 41.183082],
 [-8.613675, 41.183136],
 [-8.613702, 41.183145],
 [-8.613288, 41.18319],
 [-8.610813, 41.184],
 [-8.607474, 41.184648],
 [-8.604018, 41.183892],
 [-8.601768, 41.183253],
 [-8.601588, 41.182632],
 [-8.601957, 41.181831],
 [-8.601903, 41.181795],
 [-8.601948, 41.181822],
 [-8.601894, 41.181813]]

In [ ]:
porto_cs.x_min, porto_cs.x_max

In [ ]:
from utils.tool_funcs import lonlat2meters

In [ ]:
lonlat2meters(lon_lat_list[0][0],lon_lat_list[0][1])

In [ ]:
point_ids = [porto_cs.get_cellid_by_point(*lonlat2meters(x[0],x[1])) for x in lon_lat_list]

In [ ]:
point_ids

In [ ]:
from ah_databricks_data_loader import DatabricksDataLoader

# Instantiate the DatabricksDataLoader.
ddl = DatabricksDataLoader()

# List available shares.
shares = ddl.list_shares()

# Print shares.
print(shares)

In [21]:
builder.configs

{'spark.sql.extensions': 'io.delta.sql.DeltaSparkSessionExtension',
 'spark.sql.catalog.spark_catalog': 'org.apache.spark.sql.delta.catalog.DeltaCatalog',
 'fs.s3a.aws.credentials.provider': 'com.amazonaws.auth.ContainerCredentialsProvider',
 'spark.driver.memory': '16g',
 'spark.executor.memory': '16g',
 'spark.executor.cores': '2',
 'spark.executor.instances': '4'}

In [1]:
from ah_databricks_data_loader import DatabricksDataLoader
from ah_databricks_data_loader.spark_session_builder import SparkSessionBuilder

share_name = "sagemaker_share_prod"
schema = "datascience_scratchpad"
table = "all_traj_train"

# Instantiate the DatabricksDataLoader.
spark_params = {
    "driver_memory": "16g",
    "executor_memory": "8g",
    "executor_cores": "2",
    "executor_instances": "4"
    
}

ddl = DatabricksDataLoader( )
builder = SparkSessionBuilder(**spark_params)
builder.configs.update({"spark.local.dir":"/home/sagemaker-user/tmp"})
spark_session = builder.get_or_create_spark_session()
temp_file = ddl._get_delta_sharing_config()
config_path = ddl._create_delta_sharing_url(
    file_name=temp_file.name, share_name=share_name, schema=schema, table=table
)

df =spark_session.read.format("deltaSharing").option("responseFormat", "delta").load(config_path)

# Display the loaded DataFrame.
df.count()

:: loading settings :: url = jar:file:/home/sagemaker-user/.conda/envs/trajcl/lib/python3.12/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml


Ivy Default Cache set to: /home/sagemaker-user/.ivy2/cache
The jars for the packages stored in: /home/sagemaker-user/.ivy2/jars
io.delta#delta-sharing-spark_2.12 added as a dependency
org.apache.hadoop#hadoop-aws added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-c194df8d-4963-4e76-8e0b-e39e280e2ba3;1.0
	confs: [default]
	found io.delta#delta-sharing-spark_2.12;3.2.0 in central
	found io.delta#delta-spark_2.12;3.2.0 in central
	found io.delta#delta-storage;3.2.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
	found io.delta#delta-sharing-client_2.12;1.0.5 in central
	found org.apache.httpcomponents#httpclient;4.5.13 in central
	found org.apache.httpcomponents#httpcore;4.4.13 in central
	found commons-logging#commons-logging;1.2 in central
	found commons-codec#commons-codec;1.11 in central
	found org.apache.hadoop#hadoop-aws;3.3.1 in central
	found com.amazonaws#aws-java-sdk-bundle;1.11.901 in central
	found org.wildfly.openssl#wildfly-o

31447648

In [ ]:
count=0
for row in df.toLocalIterator():
    print(row)
    count+=1
    if count>10:
        break

In [ ]:
row['traj_id']

In [ ]:
splits = df.randomSplit([0.8, 0.1, 0.1], seed=42)  # seed for reproducibility
train_df, val_df, test_df = splits

In [ ]:
train_df.show()

In [ ]:
df_with_index = df.rdd.zipWithIndex().map(lambda x: (x[1], x[0])).toDF(["row_index", "row"])

In [ ]:
df_with_index.filter(df_with_index['row_index']==2).collect()[0]

In [ ]:
next(df.toLocalIterator())

In [7]:
df.show()

+-------+----------+--------------------+--------------------+--------------------+
| userid| traj_date|          timestamps|             wgs_seq|            merc_seq|
+-------+----------+--------------------+--------------------+--------------------+
|4421213|2022-11-13|[2022-11-13 05:42...|[[-73.781794, 42....|[[-8213351.737894...|
|4421213|2022-11-14|[2022-11-14 00:43...|[[-73.7817955, 42...|[[-8213351.904873...|
|4421213|2022-11-15|[2022-11-15 08:25...|[[-73.7743822, 42...|[[-8212526.660092...|
|4421213|2022-11-16|[2022-11-16 00:06...|[[-73.781837, 42....|[[-8213356.524632...|
|4421213|2022-11-17|[2022-11-17 00:44...|[[-73.7818355, 42...|[[-8213356.357653...|
|4421213|2022-11-18|[2022-11-18 00:40...|[[-73.7792254, 42...|[[-8213065.802650...|
|4421213|2022-11-19|[2022-11-19 00:00...|[[-73.7818073, 42...|[[-8213353.218443...|
|4421213|2022-11-20|[2022-11-20 04:59...|[[-73.7818337, 42...|[[-8213356.157277...|
|4421213|2022-11-21|[2022-11-21 00:40...|[[-73.7818223, 42...|[[-8213354.888

In [2]:
df.repartition(1000).write.parquet("/mnt/sagemaker-nvme/usa/train", mode="overwrite")

In [ ]:
import os
data_dir = "/home/sagemaker-user/TrajCL/data/nyc/train_with_ts/"
files = [os.path.join(data_dir, f) for f in os.listdir(data_dir) if f.endswith(".parquet")]
files

import pandas as pd
from tqdm import tqdm
total_count = 0
for file_path in tqdm(files):
    df = pd.read_parquet(file_path)
    total_count+=len(df)

total_count

In [ ]:
test = pd.read_parquet("/home/sagemaker-user/TrajCL/data/parquet_files/nyc_v2/part-00000-76372e3b-95b4-498e-9e85-2765482fcef5-c000.snappy.parquet")
test.head()

In [ ]:
len(test)

In [ ]:
import numpy as np
np.stack(test['merc_seq_filtered'].values[0])

In [3]:
import os
import torch
from torch.utils.data import IterableDataset
import pandas as pd
import numpy as np
class ParquetDataset(IterableDataset):
    def __init__(self, data_dir):
        self.files = [os.path.join(data_dir, f) for f in os.listdir(data_dir) if f.endswith(".parquet")]

    def __iter__(self):
        for file_path in self.files:
            df = pd.read_parquet(file_path)
            features = df["userid"].values
            for feature in features:
                yield feature

In [4]:
parquet_dataset = ParquetDataset("/mnt/sagemaker-nvme/data/usa/val")

In [5]:
from torch.utils.data import DataLoader
dl = DataLoader(parquet_dataset, batch_size=1)

In [6]:
count = 0
for batch in dl:
    print(batch)
    count+=1
    if count>10:
        break
    

tensor([1118204], dtype=torch.int32)
tensor([6679147], dtype=torch.int32)
tensor([4422568], dtype=torch.int32)
tensor([16068847], dtype=torch.int32)
tensor([13086361], dtype=torch.int32)
tensor([16079326], dtype=torch.int32)
tensor([6811073], dtype=torch.int32)
tensor([12946400], dtype=torch.int32)
tensor([2620032], dtype=torch.int32)
tensor([6800596], dtype=torch.int32)
tensor([19365363], dtype=torch.int32)
